import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col overflow-hidden bg-gray-900">
        <Header />

        <div className="h-full overflow-y-scroll">
          <div className="flex h-full flex-1 items-center justify-center">
            {children}
          </div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
